### ISSUE TITLE
Can't start steamworks API

### ISSUE THREAD

**Issue by hulifu** [ceifa/steamworks.js#119]
\git\underthegrave\eleprj\inss\steamworks.js-main\test\electron\node_modules\.store\steamworks.js@0.3.1\node_modules\steamworks.js\index.js:31 Uncaught Error: failed to init the steamworks API
    at module.exports.init (H:\git\underthegrave\eleprj\inss\steamworks.js-main\test\electron\node_modules\.store\steamworks.js@0.3.1\node_modules\steamworks.js\index.js:31:5)
    at renderer.js:3:27

run test electron but erorr .  Can't start steamworks API

**Comment by hulifu** [comment]
need run steam
