### ISSUE TITLE
Cannot start electron app with or without asar

### ISSUE THREAD

**Issue by KlutzyBubbles** [ceifa/steamworks.js#136]
Have an electron forge app built with `npm init electron-app@latest my-new-app -- --template=webpack-typescript`. When `asar` is set to `true` and it is packaged and run i get

```
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: The specified module could not be found.
\\?\C:\Users\KlutzyBubbles\AppData\Local\Temp\cfb5778c-a929-41af-ade0-4a7ded87cea2.tmp.node
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2214)
    at Module._extensions..node (node:internal/modules/cjs/loader:1343:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2441)
    at Module.load (node:internal/modules/cjs/loader:1098:32)
    at Module._load (node:internal/modules/cjs/loader:945:12)
    at c._load (node:electron/js2c/node_init:2:13672)
    at Module.require (node:internal/modules/cjs/loader:1122:19)
    at require (node:internal/modules/helpers:130:18)
    at 704 (C:\Users\KlutzyBubbles\Documents\GitHub\my-new-app\out\my-new-app-win32-x64\resources\app.asar\.webpack\main\index.js:1:284)
    at n (C:\Users\KlutzyBubbles\Documents\GitHub\my-new-app\out\my-new-app-win32-x64\resources\app.asar\.webpack\main\index.js:1:16051)

[OK]
```

When i set `asar` to `false` the app launches then instantly closes with no errors.

Removing the `steamworks.js` and packaging with or without `asar` works fine. I have been stuck for hours trying to figure out what im doing wrong but i can't seem to change anything to make it work.

**Comment by KlutzyBubbles** [comment]
I have created a project using teh command i provided in the previous message, installed steamworks.js and added the overlay to replicate the issue. 

https://github.com/KlutzyBubbles/code-holders/tree/electron-forge-issue
