### ISSUE TITLE
Failed build: use of undeclared type `FromNapiValue`

### ISSUE THREAD

**Issue by dfabulich** [ceifa/steamworks.js#80]
It's been a while since I've built steamworks.js from scratch, but it's now failing to build for me. I tried `git clean -xdf` and re-running `npm install`, and I keep getting the same failure.

I assume it's a versioning mismatch? But I can't see how/why that would be.

```
% npm run build:debug

> steamworks.js@0.1.0 build:debug
> node build

   Compiling proc-macro2 v1.0.56
   Compiling quote v1.0.26
   Compiling unicode-ident v1.0.8
   Compiling serde_derive v1.0.160
   Compiling memchr v2.5.0
   Compiling serde v1.0.160
   Compiling libc v0.2.141
   Compiling syn v1.0.109
   Compiling autocfg v1.1.0
   Compiling semver v1.0.17
   Compiling unicode-segmentation v1.10.1
   Compiling thiserror v1.0.40
   Compiling steamworks-sys v0.10.0 (https://github.com/Noxime/steamworks-rs.git#30904ebe)
   Compiling regex-syntax v0.6.29
   Compiling serde_json v1.0.95
   Compiling once_cell v1.17.1
   Compiling pin-project-lite v0.2.9
   Compiling ryu v1.0.13
   Compiling napi-build v2.0.1
   Compiling itoa v1.0.6
   Compiling bitflags v2.1.0
   Compiling bitflags v1.3.2
   Compiling lazy_static v1.4.0
   Compiling napi-sys v2.2.3
   Compiling convert_case v0.6.0
   Compiling tokio v1.27.0
   Compiling steamworksjs v0.0.1 (/Users/dfabulich/git/steamworks.js)
   Compiling aho-corasick v0.7.20
   Compiling regex v1.7.3
   Compiling syn v2.0.13
   Compiling num_cpus v1.15.0
   Compiling napi-derive-backend v1.0.49
   Compiling thiserror-impl v1.0.40
   Compiling ctor v0.2.0
   Compiling napi-derive v2.12.3
   Compiling steamworks v0.10.0 (https://github.com/Noxime/steamworks-rs.git#30904ebe)
   Compiling napi v2.12.4
error[E0433]: failed to resolve: use of undeclared type `FromNapiValue`
  --> src/api/callback.rs:3:1
   |
3  | #[napi]
   | ^^^^^^^
   |
  ::: /Users/dfabulich/.cargo/registry/src/github.com-1ecc6299db9ec823/napi-2.12.4/src/bindgen_runtime/js_values.rs:60:1
   |
60 | pub trait ToNapiValue {
   | --------------------- similarly named trait `ToNapiValue` defined here
   |
   = note: this error originates in the attribute macro `napi` (in Nightly builds, run with -Z macro-backtrace for more info)
help: a trait with a similar name exists
   |
3  | ToNapiValue
   |
help: consider importing this trait
   |
5  |     use napi::bindgen_prelude::FromNapiValue;
   |

error[E0433]: failed to resolve: use of undeclared type `FromNapiValue`
  --> src/api/matchmaking.rs:3:1
   |
3  | #[napi]
   | ^^^^^^^
   |
  ::: /Users/dfabulich/.cargo/registry/src/github.com-1ecc6299db9ec823/napi-2.12.4/src/bindgen_runtime/js_values.rs:60:1
   |
60 | pub trait ToNapiValue {
   | --------------------- similarly named trait `ToNapiValue` defined here
   |
   = note: this error originates in the attribute macro `napi` (in Nightly builds, run with -Z macro-backtrace for more info)
help: a trait with a similar name exists
   |
3  | ToNapiValue
   |
help: consider importing this trait
   |
5  |     use napi::bindgen_prelude::FromNapiValue;
   |

error[E0433]: failed to resolve: use of undeclared type `FromNapiValue`
  --> src/api/networking.rs:3:1
   |
3  | #[napi]
   | ^^^^^^^
   |
  ::: /Users/dfabulich/.cargo/registry/src/github.com-1ecc6299db9ec823/napi-2.12.4/src/bindgen_runtime/js_values.rs:60:1
   |
60 | pub trait ToNapiValue {
   | --------------------- similarly named trait `ToNapiValue` defined here
   |
   = note: this error originates in the attribute macro `napi` (in Nightly builds, run with -Z macro-backtrace for more info)
help: a trait with a similar name exists
   |
3  | ToNapiValue
   |
help: consider importing this trait
   |
5  |     use napi::bindgen_prelude::FromNapiValue;
   |

For more information about this error, try `rustc --explain E0433`.
error: could not compile `steamworksjs` due to 3 previous errors
Internal Error: Command failed: cargo build
    at checkExecSyncError (node:child_process:885:11)
    at Object.execSync (node:child_process:957:15)
    at BuildCommand.<anonymous> (/Users/dfabulich/git/steamworks.js/node_modules/@napi-rs/cli/scripts/index.js:11503:30)
    at Generator.next (<anonymous>)
    at /Users/dfabulich/git/steamworks.js/node_modules/@napi-rs/cli/scripts/index.js:3512:71
    at new Promise (<anonymous>)
    at __awaiter$1 (/Users/dfabulich/git/steamworks.js/node_modules/@napi-rs/cli/scripts/index.js:3508:12)
    at BuildCommand.execute (/Users/dfabulich/git/steamworks.js/node_modules/@napi-rs/cli/scripts/index.js:11283:16)
    at BuildCommand.validateAndExecute (/Users/dfabulich/git/steamworks.js/node_modules/@napi-rs/cli/scripts/index.js:2038:37)

/Users/dfabulich/git/steamworks.js/build.js:46
            throw err;
            ^
1
(Use `node --trace-uncaught ...` to show where the exception was thrown)

Node.js v19.9.0
```

**Comment by ceifa** [comment]
Can confirm, same error here.

**Comment by dfabulich** [comment]
Do you have any idea what's going on here? I see that you pushed out a new version literally two weeks ago, but based on my bisect, the build has been broken since July 2022?!

**Comment by ceifa** [comment]
It is a dependency problem, because we don't use exact versions or cargo.lock, git bisect will not work as expected. The only way to understand it's start changing dependencies version and see what works.

Probably there is something we can do on code to fix too...

**Comment by dfabulich** [comment]
Would you accept a PR that brings Cargo.lock back?
